services:
  - type: web
    name: live-polling-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: pulsepoll-secret-key-2026-aruna-secure
      - key: MONGO_DB_NAME
        value: livepolling
      - key: GIN_MODE
        value: release
